# Generated by Django 3.1.3 on 2021-03-10 00:16

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=60)),
                ('bus_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bus_Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_stop_name', models.CharField(max_length=60)),
                ('bus_stop_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_arrival', to='tickets.bus_stop')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_bus', to='tickets.bus')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_departure', to='tickets.bus_stop')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=50)),
                ('phone_number', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('ticket', models.ManyToManyField(blank=True, related_name='passengers', to='tickets.Ticket')),
            ],
        ),
    ]
