# Generated by Django 3.1.3 on 2021-03-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_stop_name', models.CharField(max_length=60)),
                ('bus_stop_code', models.CharField(max_length=10)),
            ],
        ),
    ]
