# Generated by Django 3.1.3 on 2021-03-05 16:35

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_bus_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessenger_name', models.CharField(max_length=50)),
                ('phone_number', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('departure', models.CharField(max_length=50)),
                ('arrival', models.CharField(max_length=50)),
                ('bus_code', models.CharField(max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
