# Generated by Django 3.1.3 on 2021-03-05 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bus_name',
            field=models.ForeignKey(default='Bus', on_delete=django.db.models.deletion.CASCADE, related_name='r_bus_name', to='tickets.bus'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_arrival', to='tickets.bus_stop'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='bus_code',
            field=models.ForeignKey(default='Bus Code', on_delete=django.db.models.deletion.CASCADE, related_name='r_bus_code', to='tickets.bus'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_departure', to='tickets.bus_stop'),
        ),
    ]
